### ISSUE TITLE
Comple error when following step 3

### ISSUE THREAD

**Issue by slipszenko** [iOSAppDevelopmentwithSwiftinAction/DistanceConverter#1]
https://github.com/iOSAppDevelopmentwithSwiftinAction/DistanceConverter/blob/9632d9ce7e692cc9f04febcbac7ef26de134f7c8/DistanceConverter/ViewController.swift#L31

In step 3 under "CONNECTING ACTIONS FROM CODE" you say:

> You could also remove the @IBAction keyword from the convertToMiles()
method because this is called from code now, and isn’t connected to an event in
Interface Builder. If you forget to do this, don’t worry; it’s not strictly necessary.

But if you remove `@IBAction` you get the following compiler error:

> [...]/DistanceConverter/DistanceConverter/ViewController.swift:25:45: Argument of '#selector' refers to instance method 'convertToMiles' that is not exposed to Objective-C
> [...]/DistanceConverter/DistanceConverter/ViewController.swift:35:10: Add '@objc' to expose this instance method to Objective-C

If you use the fix button and to add `@objc ` it works again. Not sure if that's worth mentioning in there? Or If I've just set things up wrong somewhere.

I'm enjoying the book, thanks!

**Comment by iOSAppDevelopmentwithSwiftinAction** [comment]
Hi @slipszenko, glad to hear you're enjoying the book! 

Sorry it took me a while to notice your comment here! Well spotted, due to changes in Swift this step was made redundant. (It was removed in [the errata](https://manning-content.s3.amazonaws.com/download/4/20f1859-db4c-46e6-a1cf-2879f7753686/Grummitt_iOSDevelopmentwithSwift__err11.html) for the book.) 

If you're interested to know a bit more of the why read on:
In Swift 4, functions in Swift were no longer exposed by default to Objective-C. Instead, if you needed your function to be interoperable with Objective-C, you needed to specify this with the keyword '@objc'. You can see the swift evolution proposal for this change [here](https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md). 

The `addTarget` method is triggered by Objective-C under the hood, so it requires your method to be tagged as '@objc'.

So - solution 1 is you could remove the `@IBAction` keyword (as this method was no longer being called by interface builder) and replace it with the `@objc` keyword.

Another point to be aware of is that the keyword '@IBAction' automatically triggered a method to be exposed to Objective-C. 

So, it doesn't hurt anything that your method is exposed to Interface Builder with the `@IBAction` even though you're not calling it from Interface Builder, solution 2  is to just leave it as is, with the `@IBAction`. i.e. do nothing!
